Refactor(code): main & dev yml added

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,10 +1,9 @@
-name: Deploy to Vercel
+name: Deploy to Prod & Dev
 
 on:
-  pull_request:
+  push:
     branches:
-      - "*"
-
+      - main
 jobs:
   lint:
     runs-on: ubuntu-latest
@@ -24,9 +23,11 @@ jobs:
         run: npm run lint
 
   deploy:
-    runs-on: ubuntu-latest
     needs: lint
-
+    runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        environment: [development, production] # this run two environment parallel
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
@@ -42,6 +43,9 @@ jobs:
       - name: Remove .vercel directory
         run: rm -rf .vercel
 
+      - name: Create env file
+        run: echo "NEXT_PUBLIC_ENV=${{ matrix.environment }}" > .env
+
       - name: Build project
         run: npm run build
 
@@ -52,12 +56,18 @@ jobs:
           VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
         run: |
           npm install -g vercel
-            # Preview deployment
-            vercel --token $VERCEL_TOKEN --scope $VERCEL_ORG_ID | tee deployment.log
+
+          # Deploy based on environment
+          if [ "${{ matrix.environment }}" == "production" ]; then
+            DEPLOYMENT_URL=$(vercel --prod --token $VERCEL_TOKEN | tee deployment.log | grep -o 'https:\/\/[a-zA-Z0-9.-]*\.vercel\.app')
+          else
+            DEPLOYMENT_URL=$(vercel --token $VERCEL_TOKEN --scope $VERCEL_ORG_ID --yes | tee deployment.log | grep -o 'https:\/\/[a-zA-Z0-9.-]*\.vercel\.app')
+            # Set alias for development
+            vercel alias set $(echo $DEPLOYMENT_URL | sed 's|https\?://||') dev.degenmarkets.com --token $VERCEL_TOKEN --scope $VERCEL_ORG_ID || {
+              echo "Failed to set alias. Check domain permissions."
+              exit 1
+            }
           fi
 
-          # Extract deployment URL
-          DEPLOYMENT_URL=$(grep -o 'https:\/\/[a-zA-Z0-9.-]*\.vercel\.app' deployment.log)
-          echo 
-          echo "-------------------Deployment successful!--------------------"
+          echo "Deployment successful!"
           echo "Access your application at: $DEPLOYMENT_URL"
